### ISSUE TITLE
Fix exception rethrows

### ISSUE THREAD

**Issue by lorddev** [vinguan/restion#3]
Remove instances of `catch (Exception ex) { throw; }`.

**Comment by vinguan** [comment]
@lorddev Where did you got this issue?

**Comment by lorddev** [comment]
@vinguan It was pointed out to me by another developer on my team, but I just searched your repository and saw that the offending class is `Restion.Tests/JsonTests/JSONPlaceholderCodePostsTests.cs` ... So, since the offender is a unit test class I guess it doesn't qualify as a bug. Thanks.

**Comment by vinguan** [comment]
@lorddev I see. Just for curiosity. You guys are using Restion on your projects?

**Comment by lorddev** [comment]
We were just getting an idea of your coding style.
